//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB2_Register_Enums.h>

/*
 //-----------------------------------------------------------------------------
 // RTC0ALARM_ISR
 //-----------------------------------------------------------------------------
 //
 // RTC0ALARM ISR Content goes here. Remember to clear flag bits:
 // RTC0CN0::ALRM (RTC Alarm Event Flag and Auto Reset Enable)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (RTC0ALARM_ISR, RTC0ALARM_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // TIMER0_ISR
 //-----------------------------------------------------------------------------
 //
 // TIMER0 ISR Content goes here. Remember to clear flag bits:
 // TCON::TF0 (Timer 0 Overflow Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // TIMER2_ISR
 //-----------------------------------------------------------------------------
 //
 // TIMER2 ISR Content goes here. Remember to clear flag bits:
 // TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
 // TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // SMBUS0_ISR
 //-----------------------------------------------------------------------------
 //
 // SMBUS0 ISR Content goes here. Remember to clear flag bits:
 // SMB0CN0::SI (SMBus Interrupt Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (SMBUS0_ISR, SMBUS0_IRQn)
 {

 }

 //-----------------------------------------------------------------------------
 // TIMER3_ISR
 //-----------------------------------------------------------------------------
 //
 // TIMER3 ISR Content goes here. Remember to clear flag bits:
 // TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
 // TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
 //
 //-----------------------------------------------------------------------------
 SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
 {

 }
 */
