//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_SleepMode_from_RESET(void);
extern void enter_ClockMode_from_SleepMode(void);
extern void enter_SleepMode_from_ClockMode(void);
extern void enter_RunMode_from_ClockMode(void);
extern void enter_SleepMode_from_RunMode(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void PCA_0_enter_SleepMode_from_RESET(void);
extern void PCACH_5_enter_SleepMode_from_RESET(void);
extern void VREG_0_enter_SleepMode_from_RESET(void);
extern void ADC_0_enter_SleepMode_from_RESET(void);
extern void VREF_0_enter_SleepMode_from_RESET(void);
extern void PORTS_0_enter_SleepMode_from_RESET(void);
extern void PORTS_1_enter_SleepMode_from_RESET(void);
extern void PORTS_2_enter_SleepMode_from_RESET(void);
extern void PBCFG_0_enter_SleepMode_from_RESET(void);
extern void RSTSRC_0_enter_SleepMode_from_RESET(void);
extern void RTC_0_enter_SleepMode_from_RESET(void);
extern void CLOCK_0_enter_SleepMode_from_RESET(void);
extern void FLASH_0_enter_SleepMode_from_RESET(void);
extern void TIMER_SETUP_0_enter_SleepMode_from_RESET(void);
extern void SMBUS_0_enter_SleepMode_from_RESET(void);
extern void INTERRUPT_0_enter_SleepMode_from_RESET(void);
extern void PMU_0_enter_SleepMode_from_RESET(void);
extern void PCA_0_enter_ClockMode_from_SleepMode(void);
extern void ADC_0_enter_ClockMode_from_SleepMode(void);
extern void PORTS_0_enter_ClockMode_from_SleepMode(void);
extern void PBCFG_0_enter_ClockMode_from_SleepMode(void);
extern void PMU_0_enter_ClockMode_from_SleepMode(void);
extern void PCA_0_enter_SleepMode_from_ClockMode(void);
extern void ADC_0_enter_SleepMode_from_ClockMode(void);
extern void PORTS_0_enter_SleepMode_from_ClockMode(void);
extern void PBCFG_0_enter_SleepMode_from_ClockMode(void);
extern void PMU_0_enter_SleepMode_from_ClockMode(void);
extern void PCA_0_enter_RunMode_from_ClockMode(void);
extern void PCACH_0_enter_RunMode_from_ClockMode(void);
extern void PCACH_1_enter_RunMode_from_ClockMode(void);
extern void ADC_0_enter_RunMode_from_ClockMode(void);
extern void VREF_0_enter_RunMode_from_ClockMode(void);
extern void PBCFG_0_enter_RunMode_from_ClockMode(void);
extern void HFOSC_0_enter_RunMode_from_ClockMode(void);
extern void CLOCK_0_enter_RunMode_from_ClockMode(void);
extern void TIMER01_0_enter_RunMode_from_ClockMode(void);
extern void TIMER16_2_enter_RunMode_from_ClockMode(void);
extern void TIMER16_3_enter_RunMode_from_ClockMode(void);
extern void TIMER_SETUP_0_enter_RunMode_from_ClockMode(void);
extern void SMBUS_0_enter_RunMode_from_ClockMode(void);
extern void INTERRUPT_0_enter_RunMode_from_ClockMode(void);
extern void PCA_0_enter_SleepMode_from_RunMode(void);
extern void PCACH_0_enter_SleepMode_from_RunMode(void);
extern void PCACH_1_enter_SleepMode_from_RunMode(void);
extern void ADC_0_enter_SleepMode_from_RunMode(void);
extern void VREF_0_enter_SleepMode_from_RunMode(void);
extern void PORTS_0_enter_SleepMode_from_RunMode(void);
extern void PBCFG_0_enter_SleepMode_from_RunMode(void);
extern void CLOCK_0_enter_SleepMode_from_RunMode(void);
extern void HFOSC_0_enter_SleepMode_from_RunMode(void);
extern void TIMER01_0_enter_SleepMode_from_RunMode(void);
extern void TIMER16_2_enter_SleepMode_from_RunMode(void);
extern void TIMER16_3_enter_SleepMode_from_RunMode(void);
extern void TIMER_SETUP_0_enter_SleepMode_from_RunMode(void);
extern void SMBUS_0_enter_SleepMode_from_RunMode(void);
extern void INTERRUPT_0_enter_SleepMode_from_RunMode(void);
extern void PMU_0_enter_SleepMode_from_RunMode(void);
// [Config(Per-Module Mode)Transition Prototypes]$

#endif

